# Generated by Django 3.1.7 on 2021-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganj', '0003_auto_20210813_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Author'),
        ),
    ]
