# Generated by Django 3.1.7 on 2021-08-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhf', '0002_auto_20210813_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
